version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${database_name}
      POSTGRES_PASSWORD: ${database_password}
      POSTGRES_USER: ${database_username}
    ports:
      - '${database_port:-5433}:5432'
    volumes:
      - ./src/main/resources/docker:/docker-entrypoint-initdb.d
  appl:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: src/main/docker
    container_name: appl
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/${database_name}
      - SPRING_DATASOURCE_USERNAME=${spring_datasource_username}
      - SPRING_DATASOURCE_PASSWORD=${spring_database_password}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update